apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-cmap
  namespace: mlflow
data:
  init.sql: |
    CREATE SCHEMA mlflow AUTHORIZATION mlflowuser;
    ALTER DATABASE mlflow OWNER TO mlflowuser;
    GRANT ALL PRIVILEGES ON DATABASE mlflow TO mlflowuser;
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: mlflow-postgres
  namespace: mlflow
spec:
  port: 5432
  users:
    - name: mlflowuser
      databases:
        - mlflow
  databaseInitSQL:
    name: mlflow-cmap
    key: init.sql
  backups:
    pgbackrest:
      repos:
        - volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
          name: repo1
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      replicas: 1
      name: mlflow-postgres
  postgresVersion: 15
